import { faWhatsapp } from '@fortawesome/free-brands-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faAddressBook,
  faAlignLeft,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown19,
  faArrowDown91,
  faArrowDownAZ,
  faArrowDownShortWide,
  faArrowDownWideShort,
  faArrowDownZA,
  faArrowLeft,
  faArrowRight,
  faArrowRotateLeft,
  faArrowTrendDown,
  faArrowTrendUp,
  faArrowsRotate,
  faAsterisk,
  faBagShopping,
  faBan,
  faBarcode,
  faBarsStaggered,
  faBell,
  faBolt,
  faBold,
  faBoxesStacked,
  faBuilding,
  faBuildingColumns,
  faCalculator,
  faCalendar,
  faCalendarDays,
  faCaretDown,
  faCaretRight,
  faCaretUp,
  faCartFlatbed,
  faCartPlus,
  faCartShopping,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleDollarToSlot,
  faCircleExclamation,
  faCircleInfo,
  faCircleQuestion,
  faCircleXmark,
  faClock,
  faCloudArrowUp,
  faCode,
  faCodeBranch,
  faCompress,
  faCopy,
  faCreditCard,
  faDatabase,
  faDivide,
  faDollarSign,
  faDownload,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faExpand,
  faEye,
  faEyeSlash,
  faFile,
  faFileCirclePlus,
  faFileExcel,
  faFileImage,
  faFileInvoiceDollar,
  faFileLines,
  faFilePdf,
  faFilter,
  faFire,
  faFloppyDisk,
  faGear,
  faGlobe,
  faGrip,
  faGripLines,
  faHashtag,
  faHeading,
  faHeart,
  faHeadset,
  faHome,
  faIdCard,
  faImage,
  faInbox,
  faInfo,
  faItalic,
  faKey,
  faLightbulb,
  faLinkSlash,
  faList,
  faListOl,
  faListUl,
  faLock,
  faMagnifyingGlass,
  faMessage,
  faMinus,
  faMoneyBillTransfer,
  faMoneyBillWave,
  faMultiply,
  faParagraph,
  faPencil,
  faPercent,
  faPhone,
  faPlus,
  faPrint,
  faQrcode,
  faQuoteLeft,
  faReceipt,
  faRectangleList,
  faReplyAll,
  faRightLeft,
  faRightToBracket,
  faRocket,
  faRotateRight,
  faShield,
  faShieldHalved,
  faShop,
  faSign,
  faSortDown,
  faSortUp,
  faSquareCaretDown,
  faSquareMinus,
  faSquarePen,
  faSquarePlus,
  faStar,
  faStop,
  faStrikethrough,
  faSubscript,
  faSubtract,
  faSuperscript,
  faSuitcaseMedical,
  faTags,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faUnderline,
  faUpRightAndDownLeftFromCenter,
  faUpload,
  faUser,
  faUserCheck,
  faUserCog,
  faUserPlus,
  faUserTie,
  faUsers,
  faWarehouse,
  faWrench,
  faXmark,
  faBug,
  faLocationDot,
  faSpinner,
} from '@fortawesome/free-solid-svg-icons';

export const iconGlyphs: Record<string, IconDefinition> = {
  addressBook: faAddressBook,
  alignLeft: faAlignLeft,
  anglesLeft: faAnglesLeft,
  anglesRight: faAnglesRight,
  arrowDown19: faArrowDown19,
  arrowDown91: faArrowDown91,
  arrowDownAz: faArrowDownAZ,
  arrowDownShortWide: faArrowDownShortWide,
  arrowDownWideShort: faArrowDownWideShort,
  arrowDownZa: faArrowDownZA,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowRotateLeft: faArrowRotateLeft,
  arrowTrendDown: faArrowTrendDown,
  arrowTrendUp: faArrowTrendUp,
  arrowsRotate: faArrowsRotate,
  asterisk: faAsterisk,
  bagShopping: faBagShopping,
  ban: faBan,
  barcode: faBarcode,
  barsStaggered: faBarsStaggered,
  bell: faBell,
  bolt: faBolt,
  bold: faBold,
  boxesStacked: faBoxesStacked,
  bug: faBug,
  building: faBuilding,
  buildingColumns: faBuildingColumns,
  calculator: faCalculator,
  calendar: faCalendar,
  calendarDays: faCalendarDays,
  caretDown: faCaretDown,
  caretRight: faCaretRight,
  caretUp: faCaretUp,
  cartFlatbed: faCartFlatbed,
  cartPlus: faCartPlus,
  cartShopping: faCartShopping,
  chartColumn: faChartColumn,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  circleCheck: faCircleCheck,
  circleDollarToSlot: faCircleDollarToSlot,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,
  circleQuestion: faCircleQuestion,
  circleXmark: faCircleXmark,
  clock: faClock,
  cloudArrowUp: faCloudArrowUp,
  code: faCode,
  codeBranch: faCodeBranch,
  compress: faCompress,
  copy: faCopy,
  creditCard: faCreditCard,
  database: faDatabase,
  divide: faDivide,
  dollarSign: faDollarSign,
  download: faDownload,
  ellipsis: faEllipsis,
  ellipsisVertical: faEllipsisVertical,
  envelope: faEnvelope,
  expand: faExpand,
  eye: faEye,
  eyeSlash: faEyeSlash,
  file: faFile,
  fileCirclePlus: faFileCirclePlus,
  fileExcel: faFileExcel,
  fileImage: faFileImage,
  fileInvoiceDollar: faFileInvoiceDollar,
  fileLines: faFileLines,
  filePdf: faFilePdf,
  filter: faFilter,
  fire: faFire,
  floppyDisk: faFloppyDisk,
  gear: faGear,
  globe: faGlobe,
  grip: faGrip,
  gripLines: faGripLines,
  hashtag: faHashtag,
  heading: faHeading,
  heart: faHeart,
  headset: faHeadset,
  home: faHome,
  idCard: faIdCard,
  image: faImage,
  inbox: faInbox,
  info: faInfo,
  italic: faItalic,
  key: faKey,
  lightbulb: faLightbulb,
  linkSlash: faLinkSlash,
  list: faList,
  listOl: faListOl,
  listUl: faListUl,
  lock: faLock,
  locationDot: faLocationDot,
  magnifyingGlass: faMagnifyingGlass,
  message: faMessage,
  minus: faMinus,
  moneyBillTransfer: faMoneyBillTransfer,
  moneyBillWave: faMoneyBillWave,
  multiply: faMultiply,
  paragraph: faParagraph,
  pencil: faPencil,
  percent: faPercent,
  phone: faPhone,
  plus: faPlus,
  print: faPrint,
  qrcode: faQrcode,
  quoteLeft: faQuoteLeft,
  receipt: faReceipt,
  rectangleList: faRectangleList,
  replyAll: faReplyAll,
  rightLeft: faRightLeft,
  rightToBracket: faRightToBracket,
  rocket: faRocket,
  rotateRight: faRotateRight,
  shield: faShield,
  shieldHalved: faShieldHalved,
  shop: faShop,
  sign: faSign,
  sortDown: faSortDown,
  sortUp: faSortUp,
  squareCaretDown: faSquareCaretDown,
  squareMinus: faSquareMinus,
  squarePen: faSquarePen,
  squarePlus: faSquarePlus,
  star: faStar,
  stop: faStop,
  strikethrough: faStrikethrough,
  subscript: faSubscript,
  subtract: faSubtract,
  superscript: faSuperscript,
  suitcaseMedical: faSuitcaseMedical,
  tags: faTags,
  trash: faTrash,
  trashCan: faTrashCan,
  triangleExclamation: faTriangleExclamation,
  underline: faUnderline,
  upRightAndDownLeftFromCenter: faUpRightAndDownLeftFromCenter,
  upload: faUpload,
  user: faUser,
  userCheck: faUserCheck,
  userCog: faUserCog,
  userPlus: faUserPlus,
  userTie: faUserTie,
  users: faUsers,
  warehouse: faWarehouse,
  wrench: faWrench,
  xmark: faXmark,
  spinner: faSpinner,
  whatsapp: faWhatsapp as unknown as IconDefinition,
};
