
export { Setting } from './pages/setting/setting'

//database


//Todo **************Pages*************************************************
export { Compras } from './pages/Compra/Compras'
export { Home } from './pages/Home/Home'
export { Inventario } from './pages/Inventario/Inventario'
export { Login } from './pages/Login/Login'
export { NotFound } from './pages/NotFound/NotFound'
export { Registro } from './pages/Registro/Registro'
export { Ventas } from './pages/Venta/Ventas'
export { Register } from './pages/Register/Register'
export { Welcome } from './pages/Welcome'
export { Contact } from './pages/Contact.jsx'
export { Receipt } from './pages/checkout/Receipt'
export { AddCategory } from './pages/Category/AddCategory'
export { Orders } from './pages/Order/Orders'
export { AddCustomProductModal } from './component/modals/AddCustomProductModal/AddCustomProductModal'
export { SetCustomProduct } from './component/modals/CustomProduct/SetCustomProduct'


//Todo ***********Components*************************************************
export { ControlSearchProduct } from './component/ControlSearchProduct/ControlSearchProduct'
export { SearchList } from './component/ControlSearchProduct/SearchList'
export { CategoryBar } from './component/CategoryBar/CategoryBar'
export { Cart } from './component/cart/cart'
export { MultiDisplayControl } from './component/MultiDisplayControl/MultiDisplayControl'
export { RequireAuth } from './component/RequireAuth'
export { ClientControl } from './component/contact/ClientControl/ClienteControl'
/* modals */
export { BillingModal } from './component/modals/Billing/BillingModal'
export { ProductModal } from './component/modals/Product/ProductModal'
export { AddClientModal } from './component/modals/AddClient/AddClientModal'
export { Modal } from './component/modals/modal'
export { ModalManager } from './component/modals/ModalManager'
 
//Todo ******Templates**********************************************
export { StatusIndicatorDot } from './pages/Order/components/StatusIndicatorDot/StatusIndicatorDot'
export { Counter } from './templates/system/Counter/Counter'
export { FloatingMessage } from './templates/system/FloatingMessage/FloatingMessage'
export { MenuApp } from './templates/MenuApp/MenuApp'
export { MenuWebsite } from './templates/MenuWebsite/MenuWebsite'
export { MenuComponents } from './templates/MenuComponents/MenuComponents'
export { InputText, InputPassword } from './templates/system/Inputs/Input'
export { FormControl, FormGroup, FormSubGroup, FormItemGroup } from './templates/system/Form/Form'
export { Button } from './templates/system/Button/Button'
export { ExpandButton } from './templates/system/Button/ExpandButton'
export { ChevronDownButton } from './templates/system/Button/ChevronDownButton'
export { PurchaseButton } from './templates/system/Button/PurchaseButton'
export { PlusIconButton } from './templates/system/Button/PlusIconButton'
export { ButtonGroup } from './templates/system/Button/ButtonGroup'
export { DeleteButton } from './templates/system/Button/DeleteButton'
export { EditButton } from './templates/system/Button/EditButton'
export { CloseButton } from './templates/system/Button/CloseButton'
export { ArrowLeftButton, ArrowRightButton } from './templates/system/Button/ArrowButton'
export { AddClientButton } from './templates/system/Button/AddClientButton'
export { AddProductButton } from './templates/system/Button/AddProductButton'
export { CancelPurchaseBtn } from './templates/system/Button/CancelPurchaseBtn'
export { Select } from './templates/system/Select/Select.jsx'
export { Product } from './templates/system/Product/product'
export { Client } from './templates/system/client/Client'
export {Grid} from './templates/system/Grid/Grid'
export { WebName } from './templates/system/WebName/WebName'
export {Account} from './templates/Account/Account'
export {ErrorMessage} from './templates/ErrorMassage/ErrorMassage'
export {AlertHandler} from  './templates/system/Alerts/AlertHandler'
//groups 
