// Prefijos de país según GS1 (lista expandida y optimizada)
export const GS1_COUNTRY_PREFIXES = {
  // América del Norte
  '0': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '1': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '00': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '01': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '02': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '03': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '04': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '05': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '06': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '07': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '08': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '09': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '10': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '11': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '12': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  '13': { country: 'Estados Unidos y Canadá', region: 'América del Norte' },
  
  // América Central y Caribe
  '740': { country: 'Guatemala', region: 'América Central' },
  '741': { country: 'El Salvador', region: 'América Central' },
  '742': { country: 'Honduras', region: 'América Central' },
  '743': { country: 'Nicaragua', region: 'América Central' },
  '744': { country: 'Costa Rica', region: 'América Central' },
  '745': { country: 'Panamá', region: 'América Central' },
  '746': { country: 'República Dominicana', region: 'El Caribe' },
  '750': { country: 'México', region: 'América del Norte' },
  
  // América del Sur
  '759': { country: 'Venezuela', region: 'América del Sur' },
  '770': { country: 'Colombia', region: 'América del Sur' },
  '773': { country: 'Uruguay', region: 'América del Sur' },
  '775': { country: 'Perú', region: 'América del Sur' },
  '777': { country: 'Bolivia', region: 'América del Sur' },
  '778': { country: 'Argentina', region: 'América del Sur' },
  '779': { country: 'Argentina', region: 'América del Sur' },
  '780': { country: 'Chile', region: 'América del Sur' },
  '784': { country: 'Paraguay', region: 'América del Sur' },
  '789': { country: 'Brasil', region: 'América del Sur' },
  '790': { country: 'Brasil', region: 'América del Sur' },
  
  // Europa
  '30': { country: 'Francia', region: 'Europa' },
  '31': { country: 'Francia', region: 'Europa' },
  '32': { country: 'Francia', region: 'Europa' },
  '33': { country: 'Francia', region: 'Europa' },
  '34': { country: 'Francia', region: 'Europa' },
  '35': { country: 'Francia', region: 'Europa' },
  '36': { country: 'Francia', region: 'Europa' },
  '37': { country: 'Francia', region: 'Europa' },
  '380': { country: 'Bulgaria', region: 'Europa' },
  '383': { country: 'Eslovenia', region: 'Europa' },
  '385': { country: 'Croacia', region: 'Europa' },
  '387': { country: 'Bosnia y Herzegovina', region: 'Europa' },
  '389': { country: 'Montenegro', region: 'Europa' },
  '40': { country: 'Alemania', region: 'Europa' },
  '41': { country: 'Alemania', region: 'Europa' },
  '42': { country: 'Alemania', region: 'Europa' },
  '43': { country: 'Alemania', region: 'Europa' },
  '44': { country: 'Alemania', region: 'Europa' },
  '45': { country: 'Japón', region: 'Asia' },
  '46': { country: 'Rusia', region: 'Europa/Asia' },
  '470': { country: 'Kirguistán', region: 'Asia' },
  '471': { country: 'Taiwán', region: 'Asia' },
  '474': { country: 'Estonia', region: 'Europa' },
  '475': { country: 'Letonia', region: 'Europa' },
  '476': { country: 'Azerbaiyán', region: 'Asia' },
  '477': { country: 'Lituania', region: 'Europa' },
  '478': { country: 'Uzbekistán', region: 'Asia' },
  '479': { country: 'Sri Lanka', region: 'Asia' },
  '480': { country: 'Filipinas', region: 'Asia' },
  '481': { country: 'Bielorrusia', region: 'Europa' },
  '482': { country: 'Ucrania', region: 'Europa' },
  '484': { country: 'Moldavia', region: 'Europa' },
  '485': { country: 'Armenia', region: 'Asia' },
  '486': { country: 'Georgia', region: 'Asia' },
  '487': { country: 'Kazajistán', region: 'Asia' },
  '488': { country: 'Tayikistán', region: 'Asia' },
  '489': { country: 'Hong Kong', region: 'Asia' },
  '49': { country: 'Japón', region: 'Asia' },
  '50': { country: 'Reino Unido', region: 'Europa' },
  '520': { country: 'Grecia', region: 'Europa' },
  '528': { country: 'Líbano', region: 'Medio Oriente' },
  '529': { country: 'Chipre', region: 'Europa' },
  '531': { country: 'Macedonia del Norte', region: 'Europa' },
  '535': { country: 'Malta', region: 'Europa' },
  '539': { country: 'Irlanda', region: 'Europa' },
  '54': { country: 'Bélgica y Luxemburgo', region: 'Europa' },
  '560': { country: 'Portugal', region: 'Europa' },
  '569': { country: 'Islandia', region: 'Europa' },
  '57': { country: 'Dinamarca', region: 'Europa' },
  '590': { country: 'Polonia', region: 'Europa' },
  '594': { country: 'Rumania', region: 'Europa' },
  '599': { country: 'Hungría', region: 'Europa' },
  '60': { country: 'Sudáfrica', region: 'África' },
  '61': { country: 'Sudáfrica', region: 'África' },
  '62': { country: 'Sudáfrica', region: 'África' },
  '64': { country: 'Finlandia', region: 'Europa' },
  '690': { country: 'China', region: 'Asia' },
  '691': { country: 'China', region: 'Asia' },
  '692': { country: 'China', region: 'Asia' },
  '693': { country: 'China', region: 'Asia' },
  '694': { country: 'China', region: 'Asia' },
  '695': { country: 'China', region: 'Asia' },
  '696': { country: 'China', region: 'Asia' },
  '697': { country: 'China', region: 'Asia' },
  '698': { country: 'China', region: 'Asia' },
  '699': { country: 'China', region: 'Asia' },
  '70': { country: 'Noruega', region: 'Europa' },
  '729': { country: 'Israel', region: 'Medio Oriente' },
  '73': { country: 'Suecia', region: 'Europa' },
  '76': { country: 'Suiza y Liechtenstein', region: 'Europa' },
  '80': { country: 'Italia', region: 'Europa' },
  '81': { country: 'Italia', region: 'Europa' },
  '82': { country: 'Italia', region: 'Europa' },
  '83': { country: 'Italia', region: 'Europa' },
  '84': { country: 'España', region: 'Europa' },
  '850': { country: 'Cuba', region: 'El Caribe' },
  '858': { country: 'Eslovaquia', region: 'Europa' },
  '859': { country: 'República Checa', region: 'Europa' },
  '860': { country: 'Serbia', region: 'Europa' },
  '865': { country: 'Mongolia', region: 'Asia' },
  '867': { country: 'Corea del Norte', region: 'Asia' },
  '868': { country: 'Turquía', region: 'Europa/Asia' },
  '869': { country: 'Turquía', region: 'Europa/Asia' },
  '87': { country: 'Países Bajos', region: 'Europa' },
  '880': { country: 'Corea del Sur', region: 'Asia' },
  '884': { country: 'Camboya', region: 'Asia' },
  '885': { country: 'Tailandia', region: 'Asia' },
  '888': { country: 'Singapur', region: 'Asia' },
  '890': { country: 'India', region: 'Asia' },
  '893': { country: 'Vietnam', region: 'Asia' },
  '896': { country: 'Pakistán', region: 'Asia' },
  '899': { country: 'Indonesia', region: 'Asia' },
  '90': { country: 'Austria', region: 'Europa' },
  '91': { country: 'Austria', region: 'Europa' },
  '93': { country: 'Australia', region: 'Oceanía' },
  '94': { country: 'Nueva Zelanda', region: 'Oceanía' },
  '955': { country: 'Malasia', region: 'Asia' },
  '958': { country: 'Macao', region: 'Asia' }
};

// Prefijos ordenados por longitud (más largos primero) - calculado una sola vez
export const PREFIXES_SORTED = Object.keys(GS1_COUNTRY_PREFIXES).sort((a, b) => b.length - a.length);

// Constantes para cálculos GTIN y UPC
export const GTIN_MULTIPLIERS = [1, 3];
export const UPC_MULTIPLIERS = [3, 1];
