import { normalizePlanEntitlements } from '../utils/planEntitlements.util.js';

const BOOTSTRAP_EFFECTIVE_AT_ISO = new Date('2026-02-21T00:00:00.000Z').toISOString();

const buildBootstrapPlanVersion = ({
  planCode,
  version,
  displayName,
  priceMonthly,
  state = 'active',
  currency = 'DOP',
  noticeWindowDays = 30,
  limits = {},
  modules = {},
  addons = {},
}) => ({
  ...normalizePlanEntitlements({
    limits,
    modules,
    addons,
  }),
  planCode,
  version,
  displayName,
  state,
  billingCycle: 'monthly',
  currency,
  priceMonthly,
  noticeWindowDays,
  effectiveAt: BOOTSTRAP_EFFECTIVE_AT_ISO,
  limits,
});

export const BUILTIN_PLAN_CODES = ['demo', 'plus', 'legacy'];

export const BILLING_PLAN_BOOTSTRAP_DEFAULTS = {
  demo: buildBootstrapPlanVersion({
    planCode: 'demo',
    version: 'demo-v01-20260221',
    displayName: 'Demo',
    priceMonthly: 0,
    limits: {
      maxBusinesses: 1,
      maxUsers: 1,
      maxProducts: 150,
      maxMonthlyInvoices: 100,
      maxClients: 200,
      maxSuppliers: 30,
      maxWarehouses: 1,
      maxOpenCashRegisters: 1,
    },
    modules: {
      sales: true,
      preorders: false,
      inventory: true,
      orders: false,
      purchases: false,
      expenses: true,
      cashReconciliation: true,
      accountsReceivable: false,
      creditNote: false,
      utility: true,
      authorizations: false,
      taxReceipt: true,
      insurance: false,
    },
    addons: {
      advancedReports: false,
      salesAnalyticsPanel: false,
      api: false,
      ai: false,
    },
  }),
  plus: buildBootstrapPlanVersion({
    planCode: 'plus',
    version: 'plus-v01-20260221',
    displayName: 'Plus',
    priceMonthly: 1500,
    limits: {
      maxBusinesses: 1,
      maxUsers: 12,
      maxProducts: 20000,
      maxMonthlyInvoices: 25000,
      maxClients: 10000,
      maxSuppliers: 3000,
      maxWarehouses: 4,
      maxOpenCashRegisters: 12,
    },
    modules: {
      sales: true,
      preorders: true,
      inventory: true,
      orders: true,
      purchases: true,
      expenses: true,
      cashReconciliation: true,
      accountsReceivable: true,
      creditNote: true,
      utility: true,
      authorizations: true,
      taxReceipt: true,
      insurance: true,
    },
    addons: {
      advancedReports: true,
      salesAnalyticsPanel: true,
      api: false,
      ai: true,
    },
  }),
  legacy: buildBootstrapPlanVersion({
    planCode: 'legacy',
    version: 'legacy-v01-20260221',
    displayName: 'Legacy',
    priceMonthly: 1500,
    limits: {
      maxBusinesses: -1,
      maxUsers: -1,
      maxProducts: -1,
      maxMonthlyInvoices: -1,
      maxClients: -1,
      maxSuppliers: -1,
      maxWarehouses: -1,
      maxOpenCashRegisters: -1,
    },
    modules: {
      sales: true,
      preorders: true,
      inventory: true,
      orders: true,
      purchases: true,
      expenses: true,
      cashReconciliation: true,
      accountsReceivable: true,
      creditNote: true,
      utility: true,
      authorizations: true,
      taxReceipt: true,
      insurance: true,
    },
    addons: {
      advancedReports: true,
      salesAnalyticsPanel: true,
      api: true,
      ai: true,
    },
  }),
};

export const listBillingPlanBootstrapDefaults = () =>
  Object.entries(BILLING_PLAN_BOOTSTRAP_DEFAULTS).map(([planCode, currentVersion]) => ({
    planCode,
    displayName: currentVersion.displayName,
    catalogStatus: 'active',
    isSystemBuiltin: true,
    activeVersionId: currentVersion.version,
    latestVersionId: currentVersion.version,
    currentVersion: JSON.parse(JSON.stringify(currentVersion)),
  }));
