import { onDocumentWritten } from 'firebase-functions/v2/firestore';

import { db, Timestamp } from '../../../core/config/firebase.js';
import {
  getPilotAccountingSettingsForBusiness,
  isAccountingRolloutEnabledForBusiness,
} from '../../../versions/v2/accounting/utils/accountingRollout.util.js';
import {
  THRESHOLD,
  asRecord,
  resolvePurchaseDocumentTotal,
  resolvePurchaseSupplierId,
  roundToTwoDecimals,
  safeNumber,
  toCleanString,
} from './payablePayments.shared.js';

const REGION = 'us-central1';
const MEMORY = '256MiB';
const NODE_VERSION = '20';

const resolveOverpaidAmount = (purchaseRecord) => {
  const total = resolvePurchaseDocumentTotal(purchaseRecord);
  const paid = safeNumber(purchaseRecord.paymentState?.paid) ?? 0;
  return roundToTwoDecimals(Math.max(paid - total, 0));
};

export const syncPurchaseSupplierCreditNote = onDocumentWritten(
  {
    document: 'businesses/{businessId}/purchases/{purchaseId}',
    region: REGION,
    memory: MEMORY,
    runtimeOpts: { nodeVersion: NODE_VERSION },
  },
  async (event) => {
    const { businessId, purchaseId } = event.params;
    const accountingSettings =
      await getPilotAccountingSettingsForBusiness(businessId);
    if (
      !isAccountingRolloutEnabledForBusiness(businessId, accountingSettings)
    ) {
      return null;
    }

    const purchaseRecord = asRecord(event.data?.after?.data());
    if (!Object.keys(purchaseRecord).length) {
      return null;
    }

    const supplierId = resolvePurchaseSupplierId(purchaseRecord);
    if (!supplierId) {
      return null;
    }

    const overpaidAmount = resolveOverpaidAmount(purchaseRecord);
    const noteId = `purchase_overpaid_${purchaseId}`;
    const noteRef = db.doc(
      `businesses/${businessId}/supplierCreditNotes/${noteId}`,
    );
    const noteSnap = await noteRef.get();
    if (overpaidAmount <= THRESHOLD && !noteSnap.exists) {
      return null;
    }

    const existingRecord = noteSnap.exists ? asRecord(noteSnap.data()) : {};
    const existingTotalAmount = roundToTwoDecimals(
      existingRecord.totalAmount ??
        existingRecord.amount ??
        existingRecord.value,
    );
    const appliedAmount = roundToTwoDecimals(
      existingRecord.appliedAmount ??
        Math.max(
          existingTotalAmount -
            roundToTwoDecimals(
              existingRecord.remainingAmount ??
                existingRecord.balance ??
                existingTotalAmount,
            ),
          0,
        ),
    );
    const nextTotalAmount =
      overpaidAmount > THRESHOLD
        ? roundToTwoDecimals(Math.max(overpaidAmount, appliedAmount))
        : roundToTwoDecimals(appliedAmount);
    const nextRemainingAmount = roundToTwoDecimals(
      Math.max(nextTotalAmount - appliedAmount, 0),
    );
    const nextStatus =
      nextTotalAmount <= THRESHOLD
        ? 'void'
        : nextRemainingAmount <= THRESHOLD
          ? 'applied'
          : 'open';

    const payload = {
      id: noteId,
      businessId,
      supplierId,
      counterpartyId: supplierId,
      sourceDocumentType: 'purchase',
      sourceDocumentId: purchaseId,
      originType: 'purchase_overpayment',
      totalAmount: nextTotalAmount,
      appliedAmount,
      remainingAmount: nextRemainingAmount,
      status: nextStatus,
      createdAt: noteSnap.exists
        ? (existingRecord.createdAt ?? Timestamp.now())
        : Timestamp.now(),
      createdBy: noteSnap.exists ? (existingRecord.createdBy ?? null) : null,
      updatedAt: Timestamp.now(),
      updatedBy: toCleanString(purchaseRecord.updatedBy) ?? null,
      metadata: {
        purchaseId,
        purchaseNumber: purchaseRecord.numberId ?? null,
        purchaseStatus:
          toCleanString(
            purchaseRecord.workflowStatus ?? purchaseRecord.status,
          ) ?? null,
        autoGenerated: true,
        overpaidAmount,
      },
    };

    await noteRef.set(payload, { merge: true });
    return null;
  },
);
